name: Node.js CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  compile:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm install
      - name: Post to a Slack channel
        if: success()
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: "C04FBTMPRT9,CAJLHAA65"
          slack-message: "GitHub build success : ${{ job.status }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      - name: Post to a Slack channel
        if: failure()
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: "C04FBTMPRT9,CAJLHAA65"
          slack-message: "Job failed: ${{ job.status }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
  test:
    runs-on: self-hosted
    needs: compile
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Unit test
        run: echo hello world

  build:
    runs-on: self-hosted
    needs: test
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Starting server - pm2
        run: |
          pm2 restart api
