name: Node.js-CI-Test
on:
  workflow_run:
    workflows: ["Node.js CI"]
    types:
      - completed
jobs:
  test:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Try to fail
        run: |
          npm test
  build:
    runs-on: self-hosted
    needs: test
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Starting pm2
        run: |
          pm2 restart api
