name: Node.js-CI-Test
on:
  workflow_run:
    workflows: ["Node.js CI"]
    types:
      - completed
jobs:
  test:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Try to fail
        run: exit 1
      - name: Cancelling parallel jobs
        if: failure()
        uses: andymckay/cancel-action@0.2
