name: Node.js-CI-Test
on:
  workflow_run:
    workflows: ["Node.js CI"]
    types:
      - completed
jobs:
  test:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Try to fail
        run: |
          exit 1
          LAST_JOB_STATUS=$(gh run list --workflow workflow_history.yaml | grep -oh "completed.*" | head -1 | awk '{print $2}')
          THIS_JOB_STATUS="${{ job.status }}"
          echo "status changed from $LAST_JOB_STATUS to $THIS_JOB_STATUS"
