name: Node.js-CI-Test
on:
  workflow_run:
    workflows: ["Node.js CI"]
    types:
      - completed
jobs:
  test:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Try to fail
        run: exit 1
      - name: Print message if we don't fail
        run: echo Should not get here
