name: Node.js CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  compile:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm install
  test:
    runs-on: self-hosted
    needs: compile
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Unit test
        run: npm run test --runInBand
  build:
    runs-on: self-hosted
    needs: test
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Starting server - pm2
        run: |
          pm2 restart api
