# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CD - Deployment
on:
  workflow_run:
    workflows: ["Node.js-CI-Test"]
    types:
      - completed
jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Starting pm2
        run: |
          pm2 restart api
